### ISSUE TITLE
在 v3.0.0 无法使用插件，需要适配

### ISSUE THREAD

**Issue by TCOTC** [TechDecryptor/pot-app-translate-plugin-transmart#1]
https://github.com/pot-app/pot-desktop/issues/848#issuecomment-2185040654

模板仓库：https://github.com/pot-app/pot-app-translate-plugin-template

**Comment by TechDecryptor** [comment]
https://github.com/TechDecryptor/pot-app-translate-plugin-transmart/releases/tag/2.0.0
