### ISSUE TITLE
Authentication is requered after adaptation to pot 3.x version

### ISSUE THREAD

**Issue by iG8R** [TechDecryptor/pot-app-translate-plugin-transmart#2]
Hi.
Before, in 2.x versions, there was no need to fill in the name and token to get translations, but after adapting to version 3.x, it always demands to enter them, otherwise the following error would occur:
`{"header":{"type":"auto_translation","ret_code":"Auth-Failed","time_cost":7,"request_id":"50c319114eb011efbe4eba0cd5d62210"},"message":"Rejected to access, please check user and token value, or contact with transmart@tencent.com"}`

Is there a way to make it work the same way as in versions 2.x, without entering any credentials?

**Comment by TechDecryptor** [comment]
You are using the built-in transmart service of pot, right? This plugin has never required a login.

**Comment by iG8R** [comment]
Yes, you are right I was talking about the built-in transmart service of pot.
Thank you very much for reminding that this plugin is different from the built-in one.
